# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 592)
        MainWindow.setStyleSheet("QLabel {\n"
"    /* Menggunakan notasi rgba untuk transparansi yang lebih pasti */\n"
"    background-color:#FFF; \n"
"    /* Pastikan warna teks sudah benar */\n"
"    color: black;\n"
"    /* Tambahkan pengaturan font untuk konsistensi */\n"
"    font-size: 30pt; \n"
"    font-weight: bold;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:#ffffff;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"\n"
"background:#00bfff;\n"
"border-radius:60px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"color:white;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"color:#00bfff;\n"
"border-radius:15px;\n"
"background:#87cefa;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    /* Background Putih */\n"
"    background-color:#e8ebea; \n"
"    \n"
"    /* Sudut Melengkung (Membulat) - Sesuaikan nilai 15px */\n"
"    border-radius: 10px; \n"
"    \n"
"    /* Garis tepi tipis abu-abu (untuk outline samar) */\n"
"    border: 1px solid #e0e0e0; \n"
"    \n"
"    /* Warna teks saat diketik */\n"
"    color: #333333; \n"
"    \n"
"    /* Padding untuk memberikan ruang di dalam input */\n"
"    padding: 10px; \n"
"    \n"
"    /* Ukuran font */\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    /* Warna teks placeholder (Username, Password) */\n"
"    color: #aaaaaa; \n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    /* Efek saat fokus: Garis tepi BIRU CERAH */\n"
"    border: 2px solid #00bfff; \n"
"    \n"
"    /* Background tetap putih saat input aktif */\n"
"    background-color: white; \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 200, 391, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(8)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 100, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setMaxLength(8)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 110, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.lineEdit.setInputMask(_translate("MainWindow", "Username"))
        self.lineEdit.setText(_translate("MainWindow", "Username"))
        self.lineEdit_2.setInputMask(_translate("MainWindow", "Password"))
        self.lineEdit_2.setText(_translate("MainWindow", "Passwor"))
        self.label.setText(_translate("MainWindow", "Form Login"))
